[build]
publish = "static"
command = "git config --global credential.helper '!f() { echo username=\${GIT_USER}; echo password=\${GIT_PASS}; }; f' && git submodule update --init --recursive && python main.py"

[[redirects]]
from = "/*"
to = "/home.html"
status = 200




